### ISSUE TITLE
pipeline_info/pipeline_dag.svg file has no access for group and other

### ISSUE THREAD

**Issue by ofrei** [BioPsyk/cleansumstats#382]
Hi, I noticed that access permissions for ``pipeline_info/pipeline_dag.svg`` are different than for other files:
![image](https://user-images.githubusercontent.com/13171449/222379436-f08f3098-3a49-4c91-a3c5-c90aae761413.png)
The issue is that group & other users get many errors if they try to copy or remove the output of cleansumstats pipeline.
From my end a better solution would be to set pipeline_info/pipeline_dag.svg permissions same as for other files, e.g. execution_trace.txt file

**Comment by pappewaio** [comment]
I will look at this directly.
