### ISSUE TITLE
Parsing CHR:POS_A1_A2 columns

### ISSUE THREAD

**Issue by ofrei** [BioPsyk/cleansumstats#384]
Hi, let me ask if the following summary stats can be directly loaded through cleansumstats pipeline. Here the Markername column has CHR:POS_A1_A2 format, with A2 being reference allele. My yaml file has col_CHR and col_POS both pointing to Markername, but col_EffectAllele and col_OtherAllele point to Allele2 and Allele1 columns, respectively. Is this supported?
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/13171449/223735449-460f456d-e473-4b54-9041-bae6c0bdca06.png">

**Comment by ofrei** [comment]
@gledauio thanks for pointing out to this case!

**Comment by pappewaio** [comment]
It should be supported!

**Comment by pappewaio** [comment]
The regexp splits on both : and _ . It is the position in the markername that is important, i.e., chr_bp_a1_a2
