### ISSUE TITLE
files in out_dbsnp folder have All_20180418 prefix regardless of which dbSNP version is actually used

### ISSUE THREAD

**Issue by ofrei** [BioPsyk/cleansumstats#411]
From what I remember 20180418 is a timestap that relates to dbSNP v151, but it also appears in file names if we use dbSNP v156
Here is an example where we deployed cleansumstats v1.5.3 using dbSNP v151, and   v1.7.0 uses dbSNP v156. The file size of the files in out_dbsnp is different but file names are the same

<img width="799" alt="image" src="https://github.com/BioPsyk/cleansumstats/assets/13171449/4dc85521-72b4-4b48-ab50-7eb59079eba2">

<img width="817" alt="image" src="https://github.com/BioPsyk/cleansumstats/assets/13171449/6f98d3c1-70fd-4edd-9711-6b47ce676c09">

**Comment by ofrei** [comment]
That a minor point - I think everything works as expected, just file name is confusing

**Comment by pappewaio** [comment]
Yes! You are right. I thought I would not change the output names in case it messes with downstream processes. But now when we know that the reference DB works as expected, I should come up with a good naming/versioning scheme.

**Comment by pappewaio** [comment]
Fixed this. PR #417
